export default [
  {
    languageOptions: {
      globals: {
        global: true,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      'logical-assignment-operators': 'off',
      'no-throw-literal': 'off',
      'prefer-exponentiation-operator': 'off', // **はES2016以降対応
      'no-irregular-whitespace': 'off', // これを設定しているとスペースで正規表現でかかる
      'array-bracket-newline': 'off',
      'no-invalid-this': 'off',
      'no-new': 'off',
      'prefer-named-capture-group': 'off',
      'no-continue': 'off', // continueをNGとするなら外さない
      'no-prototype-builtins': 'off',
      'capitalized-comments': 'off',
      'func-names': ['error', 'never'],
      'dot-notation': 'off',
      indent: ['error', 2],
      quotes: ['error', 'single'],
      'prefer-arrow-callback': 'off',
      'padded-blocks': 'off',
      'id-length': 'off',
      curly: ['error', 'multi-line'],
      'no-magic-numbers': 'off',
      'no-use-before-define': 'off',
      'vars-on-top': 'off',
      'no-var': 'off',
      'function-call-argument-newline': 'off',
      'one-var': 'off',
      'prefer-template': 'off',
      'require-unicode-regexp': 'off',
      'quote-props': ['error', 'consistent'],
      'sort-keys': 'off',
      'max-lines': 'off',
      'max-statements': 'off',
      'init-declarations': 'off',
      'sort-vars': 'off',
      'prefer-destructuring': 'off',
      'max-len': 'off',
      'dot-location': ['error', 'property'],
      'max-lines-per-function': 'off',
      'array-element-newline': 'off',
      'no-ternary': 'off',
      'max-params': 'off',
      'object-curly-spacing': ['error', 'always'],
      'function-paren-newline': ['error', 'consistent'],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'object-shorthand': 'off',
      'multiline-ternary': 'off',
      'no-extra-parens': ['error', 'all', { nestedBinaryExpressions: false }],
      'no-undefined': 'off',
      'multiline-comment-style': 'off',
      'object-property-newline': 'off',
      'no-nested-ternary': 'off',
      'no-unused-vars': ['error', { args: 'all', argsIgnorePattern: '^_' }],
      'prefer-rest-params': 'off',
      'max-statements-per-line': 'off',
      'newline-per-chained-call': 'off',
      'no-useless-escape': 'off',
      'require-await': 'off',
      'no-trailing-spaces': 'error',
      'space-infix-ops': 'error',
      'keyword-spacing': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': 'error',
    },
  },
];
